### PR TITLE
Blu3wolf ideal 12

### PR DESCRIPTION
**Pull request by Blu3wolf**
This makes a lot of changes... but basically this would pull all the changes I made to the original repo, to make it work with v0.12, into your 0.4.4 branch.

Id probably recommend making a new branch for that though.

### CODE REVIEW

**Comment by Blu3wolf** [comment]
As a side effect of this, the pistol and rifle sounds are much cooler XD

they got updated in version 12, so I pointed the NARMod files to look for the new sounds instead.

**Comment by Cooolaid** [comment]
nice. I am a audio engineer. I was thinking about redoing sound files for a few mods out there.
Still debating...lol

**Comment by Blu3wolf** [comment]
definitely some mods could use the love. Im in need of some graphics work at the moment, but its lower priority than stripping mods out.

**Comment by Cooolaid** [comment]
Get Yuoki for the graphics :)

**Comment by Blu3wolf** [comment]
I dunno, Yuoki graphics tend to look very new. Im more of a fan of the kinda stuff on the new splash screen - worn, dirty, screaming heavy industry...

The stuff needing graphics is just an icon anyway, for zinc cathodes. I guess they dont need to look grimy, so that could be a good idea actually.

**Comment by Cooolaid** [comment]
lol
I dont like the grimy old rusty look. Im more of a clean hightech newer modern look kinda graphics.
Thats why I love Yuoki stuff so much.  :P

**Comment by Blu3wolf** [comment]
yeah... Ive not looked at it extensively, but the stuff I saw just seemed too cartoonish. Probably wouldnt be a problem for an icon anyway.

**Comment by Cooolaid** [comment]
I just sent a request for you to change an icon naming.
Im hoping Im not forgetting a code or name change....lol
that would really suck....lol

**Pull request merged**
